try{
  console.log(naoExisto);

}catch(err){
  console.log('nãoExisto Não existe');
  console.log(err);
}
